# Generated by Django 2.1.4 on 2018-12-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='uname',
        ),
    ]
