# Generated by Django 2.1.4 on 2019-01-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_img_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img_table',
            name='email',
        ),
    ]
