# Generated by Django 2.1.4 on 2019-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_remove_img_table_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_table',
            name='uid',
            field=models.CharField(default=2, max_length=140),
            preserve_default=False,
        ),
    ]
