# Generated by Django 2.1.4 on 2019-01-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_userpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='uid',
            new_name='userid',
        ),
    ]
