# Generated by Django 2.1.4 on 2019-01-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_userpost1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('login_time', models.CharField(max_length=40)),
                ('logout_time', models.CharField(max_length=40)),
            ],
        ),
    ]
