# Generated by Django 2.1.4 on 2019-01-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_login_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost1',
            name='fullname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userpost1',
            name='likes',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='userpost1',
            name='profilepic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userpost1',
            name='user_comments',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
