# Generated by Django 2.1.4 on 2019-01-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_auto_20190115_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost1',
            name='user_comments',
        ),
        migrations.AddField(
            model_name='userpost1',
            name='user_liked',
            field=models.CharField(max_length=1400, null=True),
        ),
    ]
