# Generated by Django 2.1.4 on 2019-01-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20190115_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost1',
            name='likes',
            field=models.CharField(default=0, max_length=140),
        ),
    ]
