# Generated by Django 2.1.4 on 2019-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20190116_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromid', models.CharField(max_length=40)),
                ('toid', models.CharField(max_length=40)),
                ('reqstatus', models.CharField(max_length=40)),
            ],
        ),
    ]
