# Generated by Django 2.1.4 on 2019-02-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmntrname', models.CharField(max_length=140)),
                ('cmntrpic', models.FileField(upload_to='')),
                ('comment', models.CharField(max_length=140)),
                ('cmntttime', models.CharField(max_length=40)),
                ('cmntrid', models.CharField(default=0, max_length=140)),
            ],
        ),
    ]
