# Generated by Django 2.1.4 on 2019-02-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='postid',
            field=models.CharField(default=0, max_length=140),
        ),
    ]
